import localFont from "next/font/local";
import ".././globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: ".././fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <div>
      <div className="cart-layout">
        <h1>
          THIS IS A CART LAYOUT
        </h1>
      </div>
      {children}
    </div>
  );
}
